### ISSUE TITLE
TypeError: Object #<Client> has no method 'connect'

### ISSUE THREAD

**Issue by pulkitsinghal** [mjackson/then-redis#32]
Did the API have any major changes I might have missed? For me, `redisClient.connect()` doesn't seem to work anymore. I hope its just a mistake on my part but thought I'd check.

**Comment by mjackson** [comment]
Yes, the `connect` method is gone now. The connection is now automatically handled for you by the node_redis library, which we now depend on.

**Comment by pulkitsinghal** [comment]
@mjackson - can you tell me which was the last version to use it? I'd rather not change my code right now.

**Comment by mjackson** [comment]
@pulkitsinghal 0.3.12. We started using node_redis in 1.0.0.
