### ISSUE TITLE
possible native promise support

### ISSUE THREAD

**Issue by bitinn** [mjackson/then-redis#33]
Not that I think bluebird is bad, but allow switching is a good idea in longterm, especially for node v0.11+ users (like me), given you are only using Promise spec API, not bluebird features, this should be easy.

eg. `native-or-bluebird` https://github.com/normalize/native-or-bluebird

**Comment by coderhaoxin** [comment]
related to https://github.com/mjackson/then-redis/pull/27

**Comment by bitinn** [comment]
oh well... pardon me.

If we can expose Promise then one can use whatever Promise needed. Native promise does have 1 advantage, it's quite memory-efficient: https://gist.github.com/bitinn/afcd4c6a56fcb10eb21c

**Comment by mjackson** [comment]
We're using native promises in 2.0.
