### ISSUE TITLE
database index as an auth username is not a thing

### ISSUE THREAD

**Issue by jonathanong** [mjackson/then-redis#38]
at least according to compose.io. if anything, make sure https://github.com/mjackson/then-redis/blob/master/Client.js#L81 is an integer before setting it as the database. usually, it's `x`

**Comment by timrwilliams** [comment]
Any plans to push a new version to NPM that includes this change? Thanks.

**Comment by jonathanong** [comment]
fwiw i've been slowly moving to https://www.npmjs.com/package/ioredis anyways just because `redis` is barely being maintained
