### ISSUE TITLE
Is this compatible with redis v1?

### ISSUE THREAD

**Issue by arathael** [mjackson/then-redis#51]
It published v1 (npm node-redis), and I was wondering if this will update to be compatible.

**Comment by arathael** [comment]
I guess this is not maintained anymore.

**Comment by zaggino** [comment]
Yeah, I switched from this to using https://github.com/NodeRedis/node_redis#promises

**Comment by aaronshaf** [comment]
@mjackson might want to hand this over to another maintainer?

**Comment by buddyp450** [comment]
@aaronshaf It doesn't need a new maintainer, it needs deprecation. See https://github.com/luin/ioredis.

**Comment by alexbeletsky** [comment]
@buddyp450 thanks for `ioredis` hint.

**Comment by mjackson** [comment]
then-redis 2 will depend on redis 2.4. I shipped a beta this morning.
